In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

### 1x1 Convolution Quiz

In [10]:
# custom init with the seed set to 0 by default 
def custom_init(shape, dtype=tf.float32, partition_info=None, seed=0): 
    return tf.random_normal(shape, dtype=dtype, seed=seed) 
 
# TODO: Use `tf.layers.conv2d` to reproduce the result of 
#       `tf.layers.dense`. 
# Set the `kernel_size` and `stride`. 
def conv_1x1(x, num_outputs): 
    kernel_size = 1 
    stride = 1 
    return tf.layers.conv2d(x, num_outputs, kernel_size, stride, 
                            kernel_initializer=custom_init) 
  
num_outputs = 2 
x = tf.constant(np.random.randn(1, 2, 2, 1), dtype=tf.float32) 
 
# `tf.layers.dense` flattens the input tensor if the rank > 2  
# and reshapes it back to the original rank as the output. 
dense_out = tf.layers.dense(x, num_outputs, 
                            kernel_initializer=custom_init) 

conv_out = conv_1x1(x, num_outputs) 
 
with tf.Session() as sess: 
    sess.run(tf.global_variables_initializer()) 
    a = sess.run(dense_out) 
    b = sess.run(conv_out) 
    print("Dense Output =\n", a, "\n") 
    print("Conv 1x1 Output =\n", b, "\n") 
    print("Same output? =", np.allclose(a, b, atol=1.e-5)) 

Dense Output =
 [[[[-0.07008168  0.36948475]
   [-0.31007883  1.63479805]]

  [[-0.16896337  0.89080894]
   [-0.13168478  0.69426876]]]] 

Conv 1x1 Output =
 [[[[-0.07008168  0.36948475]
   [-0.31007883  1.63479805]]

  [[-0.16896337  0.89080894]
   [-0.13168478  0.69426876]]]] 

Same output? = True


### Transposed Convolution Quiz

In [2]:
def upsample(x): 
    """ 
    Apply a two times upsample on x and return the result. 
    :x: 4-Rank Tensor 
    :return: TF Operation 
    """ 
    # TODO: Use `tf.layers.conv2d_transpose` 
    return tf.layers.conv2d_transpose(x, 3, (2, 2), (2, 2)) 
  
x = tf.constant(np.random.randn(1, 4, 4, 3), dtype=tf.float32) 
conv = upsample(x) 
  
with tf.Session() as sess: 
    sess.run(tf.global_variables_initializer()) 
    result = sess.run(conv) 
    print('Input Shape: {}'.format(x.get_shape())) 
    print('Output Shape: {}'.format(result.shape))

Input Shape: (1, 4, 4, 3)
Output Shape: (1, 8, 8, 3)


### Intersection over Union (IoU)  Quiz

In [11]:
def mean_iou(ground_truth, prediction, num_classes): 
    # TODO: Use `tf.metrics.mean_iou` to compute the mean IoU. 
    iou, iou_op = tf.metrics.mean_iou(ground_truth, 
                                      prediction, 
                                      num_classes) 
    return iou, iou_op 
  
ground_truth = tf.constant([ 
    [0, 0, 0, 0], 
    [1, 1, 1, 1], 
    [2, 2, 2, 2], 
    [3, 3, 3, 3]], dtype=tf.float32) 
  
prediction = tf.constant([ 
    [0, 0, 0, 0], 
    [1, 0, 0, 1], 
    [1, 2, 2, 1], 
    [3, 3, 0, 3]], dtype=tf.float32) 
  
# TODO: use `mean_iou` to compute the mean IoU 
iou, iou_op = mean_iou(ground_truth, prediction, 4) 
  
with tf.Session() as sess: 
    sess.run(tf.global_variables_initializer()) 
    # need to initialize local variables for this to run 
    # `tf.metrics.mean_iou` 
    sess.run(tf.local_variables_initializer()) 
  
    sess.run(iou_op) 
    # should be 0.53869 
    print("Mean IoU =", sess.run(iou))

Mean IoU = 0.53869
